In [53]:
import csv
import numpy as np
import pandas as pd
import fileinput
import string
import os
import matplotlib.pyplot as plt

from sklearn import preprocessing
from matplotlib import pyplot as plt

dataSet = []
Price= []

In [54]:
df=pd.read_csv('car_data.csv')

In [55]:
#dataset
df

,Price,Mileage,Make,Model,Trim,Type,Cylinder,Liter,Doors,Cruise,Sound,Leather
0,17314.10313,8221.0,Buick,Century,Sedan 4D,Sedan,6.0,3.1,4.0,1.0,1.0,1.0
1,17542.03608,9135.0,Buick,Century,Sedan 4D,Sedan,6.0,3.1,4.0,1.0,1.0,0.0
2,16218.84786,13196.0,Buick,Century,Sedan 4D,Sedan,6.0,3.1,4.0,1.0,1.0,0.0
3,17944.85692,19592.0,Buick,Lesabre,Custom Sedan 4D,Sedan,6.0,3.8,4.0,1.0,0.0,0.0
4,19027.86231,21797.0,Buick,Lesabre,Custom Sedan 4D,Sedan,6.0,3.8,4.0,1.0,0.0,1.0
5,18348.89857,23852.0,Buick,Lesabre,Custom Sedan 4D,Sedan,6.0,NaN,4.0,1.0,1.0,0.0
6,17750.88457,25040.0,Buick,Lesabre,Custom Sedan 4D,Sedan,6.0,3.8,4.0,1.0,1.0,0.0
7,17772.96968,25052.0,Buick,Lesabre,Custom Sedan 4D,Sedan,6.0,3.8,4.0,1.0,1.0,0.0
8,17394.02140,25464.0,Buick,Lesabre,Custom Sedan 4D,Sedan,6.0,3.8,4.0,1.0,1.0,0.0
9,17645.74504,27830.0,Buick,Lesabre,Custom Sedan 4D,Sedan,6.0,3.8,4.0,1.0,1.0,1.0
10,22435.20282,22287.0,Buick,Park Avenue,Sedan 4D,Sedan,6.0,3.8,4.0,1.0,1.0,1.0
11,21878.12000,23237.0,Buick,Park Avenue,Sedan 4D,NaN,6.0,NaN,4.0,1.0,1.0,0.0
12,23077.56591,23798.0,Buick,Park Avenue,Sedan 4D,Sedan,6.0,3.8,4.0,1.0,0.0,1.0
13,21698.01475,25489.0,Buick,Park Avenue,Sedan 4D,Sedan,6.0,3.8,4.0,1.0,1.0,1.0
14,21831.82292,25564.0,Buick,Park Avenue,Sedan 4D,Sedan,6.0,3.8,4.0,1.0,1.0,1.0
15,26831.19404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,26060.33535,9795.0,Buick,Park Avenue,Special Ed Ultra 4D,Sedan,6.0,3.8,4.0,1.0,1.0,0.0
17,26781.81465,12052.0,Buick,Park Avenue,Special Ed Ultra 4D,Sedan,6.0,3.8,4.0,1.0,1.0,0.0
18,26302.07428,13050.0,Buick,Park Avenue,Special Ed Ultra 4D,Sedan,6.0,3.8,4.0,1.0,1.0,0.0
19,26190.27147,17335.0,Buick,Park Avenue,Special Ed Ultra 4D,Sedan,6.0,3.8,4.0,1.0,0.0,1.0
20,40619.07227,30082.0,Cadillac,CST-V,Sedan 4D,Sedan,8.0,5.7,4.0,1.0,1.0,1.0
21,33417.96501,6598.0,Cadillac,CTS,Sedan 4D,Sedan,6.0,2.8,4.0,1.0,1.0,1.0
22,30957.08075,10625.0,Cadillac,CTS,Sedan 4D,Sedan,6.0,2.8,4.0,1.0,1.0,1.0
23,31431.13037,11013.0,Cadillac,CTS,Sedan 4D,Sedan,6.0,NaN,4.0,1.0,1.0,1.0
24,30781.51563,14937.0,Cadillac,CTS,Sedan 4D,Sedan,6.0,2.8,4.0,1.0,1.0,1.0
25,35866.58271,24415.0,Cadillac,Deville,DHS Sedan 4D,Sedan,8.0,4.6,4.0,1.0,1.0,1.0
26,35338.65369,25163.0,Cadillac,Deville,DHS Sedan 4D,Sedan,8.0,4.6,4.0,1.0,0.0,1.0
27,36154.30355,25339.0,Cadillac,Deville,DHS Sedan 4D,Sedan,8.0,4.6,4.0,1.0,1.0,1.0
28,34685.66298,25421.0,Cadillac,Deville,DHS Sedan 4D,Sedan,8.0,4.6,4.0,1.0,0.0,1.0

In [56]:
#df.Price

In [57]:
#null values
df.isnull()

,Price,Mileage,Make,Model,Trim,Type,Cylinder,Liter,Doors,Cruise,Sound,Leather
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,True,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,True,False,True,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,True,True,True,True,True,True,True,True,True,True,True
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,True,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False

In [58]:
#replaced missing values with mean
df.fillna(df.mean(), inplace=True)

In [59]:
df

,Price,Mileage,Make,Model,Trim,Type,Cylinder,Liter,Doors,Cruise,Sound,Leather
0,17314.10313,8221.000000,Buick,Century,Sedan 4D,Sedan,6.000000,3.1,4.0,1.0,1.000000,1.000000
1,17542.03608,9135.000000,Buick,Century,Sedan 4D,Sedan,6.000000,3.1,4.0,1.0,1.000000,0.000000
2,16218.84786,13196.000000,Buick,Century,Sedan 4D,Sedan,6.000000,3.1,4.0,1.0,1.000000,0.000000
3,17944.85692,19592.000000,Buick,Lesabre,Custom Sedan 4D,Sedan,6.000000,3.8,4.0,1.0,0.000000,0.000000
4,19027.86231,21797.000000,Buick,Lesabre,Custom Sedan 4D,Sedan,6.000000,3.8,4.0,1.0,0.000000,1.000000
5,18348.89857,23852.000000,Buick,Lesabre,Custom Sedan 4D,Sedan,6.000000,3.8,4.0,1.0,1.000000,0.000000
6,17750.88457,25040.000000,Buick,Lesabre,Custom Sedan 4D,Sedan,6.000000,3.8,4.0,1.0,1.000000,0.000000
7,17772.96968,25052.000000,Buick,Lesabre,Custom Sedan 4D,Sedan,6.000000,3.8,4.0,1.0,1.000000,0.000000
8,17394.02140,25464.000000,Buick,Lesabre,Custom Sedan 4D,Sedan,6.000000,3.8,4.0,1.0,1.000000,0.000000
9,17645.74504,27830.000000,Buick,Lesabre,Custom Sedan 4D,Sedan,6.000000,3.8,4.0,1.0,1.000000,1.000000
10,22435.20282,22287.000000,Buick,Park Avenue,Sedan 4D,Sedan,6.000000,3.8,4.0,1.0,1.000000,1.000000
11,21878.12000,23237.000000,Buick,Park Avenue,Sedan 4D,NaN,6.000000,3.8,4.0,1.0,1.000000,0.000000
12,23077.56591,23798.000000,Buick,Park Avenue,Sedan 4D,Sedan,6.000000,3.8,4.0,1.0,0.000000,1.000000
13,21698.01475,25489.000000,Buick,Park Avenue,Sedan 4D,Sedan,6.000000,3.8,4.0,1.0,1.000000,1.000000
14,21831.82292,25564.000000,Buick,Park Avenue,Sedan 4D,Sedan,6.000000,3.8,4.0,1.0,1.000000,1.000000
15,26831.19404,19477.821429,NaN,NaN,NaN,NaN,6.357143,3.8,4.0,1.0,0.785714,0.607143
16,26060.33535,9795.000000,Buick,Park Avenue,Special Ed Ultra 4D,Sedan,6.000000,3.8,4.0,1.0,1.000000,0.000000
17,26781.81465,12052.000000,Buick,Park Avenue,Special Ed Ultra 4D,Sedan,6.000000,3.8,4.0,1.0,1.000000,0.000000
18,26302.07428,13050.000000,Buick,Park Avenue,Special Ed Ultra 4D,Sedan,6.000000,3.8,4.0,1.0,1.000000,0.000000
19,26190.27147,17335.000000,Buick,Park Avenue,Special Ed Ultra 4D,Sedan,6.000000,3.8,4.0,1.0,0.000000,1.000000
20,40619.07227,30082.000000,Cadillac,CST-V,Sedan 4D,Sedan,8.000000,5.7,4.0,1.0,1.000000,1.000000
21,33417.96501,6598.000000,Cadillac,CTS,Sedan 4D,Sedan,6.000000,2.8,4.0,1.0,1.000000,1.000000
22,30957.08075,10625.000000,Cadillac,CTS,Sedan 4D,Sedan,6.000000,2.8,4.0,1.0,1.000000,1.000000
23,31431.13037,11013.000000,Cadillac,CTS,Sedan 4D,Sedan,6.000000,3.8,4.0,1.0,1.000000,1.000000
24,30781.51563,14937.000000,Cadillac,CTS,Sedan 4D,Sedan,6.000000,2.8,4.0,1.0,1.000000,1.000000
25,35866.58271,24415.000000,Cadillac,Deville,DHS Sedan 4D,Sedan,8.000000,4.6,4.0,1.0,1.000000,1.000000
26,35338.65369,25163.000000,Cadillac,Deville,DHS Sedan 4D,Sedan,8.000000,4.6,4.0,1.0,0.000000,1.000000
27,36154.30355,25339.000000,Cadillac,Deville,DHS Sedan 4D,Sedan,8.000000,4.6,4.0,1.0,1.000000,1.000000
28,34685.66298,25421.000000,Cadillac,Deville,DHS Sedan 4D,Sedan,8.000000,4.6,4.0,1.0,0.000000,1.000000

In [60]:
# replacing NaN values with 0
df.fillna(0, inplace=True)

In [61]:
df.isnull()

,Price,Mileage,Make,Model,Trim,Type,Cylinder,Liter,Doors,Cruise,Sound,Leather
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False

In [62]:
#dataframe 
df_new=[df.Price]

In [63]:
Price_matrix=np.reshape(df_new,(-1,1))
#Price_matrix_np = np.array(Price_matrix)
#Price_matrix_np = Price_matrix_np.reshape(df_new,(-1,1))

In [64]:
Price_matrix

array([[17314.10313],
       [17542.03608],
       [16218.84786],
       [17944.85692],
       [19027.86231],
       [18348.89857],
       [17750.88457],
       [17772.96968],
       [17394.0214 ],
       [17645.74504],
       [22435.20282],
       [21878.12   ],
       [23077.56591],
       [21698.01475],
       [21831.82292],
       [26831.19404],
       [26060.33535],
       [26781.81465],
       [26302.07428],
       [26190.27147],
       [40619.07227],
       [33417.96501],
       [30957.08075],
       [31431.13037],
       [30781.51563],
       [35866.58271],
       [35338.65369],
       [36154.30355],
       [34685.66298]])

In [65]:
#min-max scalar 
scaler =preprocessing.MinMaxScaler()
Price_matrix_minmax = scaler.fit_transform(Price_matrix)
Price_matrix_minmax

array([[0.0448871 ],
       [0.05422853],
       [0.        ],
       [0.07073743],
       [0.11512248],
       [0.08729636],
       [0.06278781],
       [0.06369293],
       [0.04816241],
       [0.05847885],
       [0.2547663 ],
       [0.23193525],
       [0.28109242],
       [0.22455395],
       [0.23003785],
       [0.43492822],
       [0.40333594],
       [0.43290449],
       [0.41324318],
       [0.40866114],
       [1.        ],
       [0.70487537],
       [0.60402038],
       [0.62344847],
       [0.59682516],
       [0.80522763],
       [0.78359139],
       [0.81701936],
       [0.75682972]])

In [66]:
#standardization
Price_matrix_scaled = preprocessing.scale(Price_matrix)
Price_matrix

array([[17314.10313],
       [17542.03608],
       [16218.84786],
       [17944.85692],
       [19027.86231],
       [18348.89857],
       [17750.88457],
       [17772.96968],
       [17394.0214 ],
       [17645.74504],
       [22435.20282],
       [21878.12   ],
       [23077.56591],
       [21698.01475],
       [21831.82292],
       [26831.19404],
       [26060.33535],
       [26781.81465],
       [26302.07428],
       [26190.27147],
       [40619.07227],
       [33417.96501],
       [30957.08075],
       [31431.13037],
       [30781.51563],
       [35866.58271],
       [35338.65369],
       [36154.30355],
       [34685.66298]])

In [67]:
#binarization
binarizer = preprocessing.Binarizer(threshold=21645.000000)
binarizer.transform(Price_matrix)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [70]:
df_new

[0     17314.10313
 1     17542.03608
 2     16218.84786
 3     17944.85692
 4     19027.86231
 5     18348.89857
 6     17750.88457
 7     17772.96968
 8     17394.02140
 9     17645.74504
 10    22435.20282
 11    21878.12000
 12    23077.56591
 13    21698.01475
 14    21831.82292
 15    26831.19404
 16    26060.33535
 17    26781.81465
 18    26302.07428
 19    26190.27147
 20    40619.07227
 21    33417.96501
 22    30957.08075
 23    31431.13037
 24    30781.51563
 25    35866.58271
 26    35338.65369
 27    36154.30355
 28    34685.66298
 Name: Price, dtype: float64]

In [73]:
#ploting for binarization
#plt.plot(Price_matrix)

In [150]:
#normalization
#Price_matrix_l1= preprocessing.normalize(Price_matrix, norm='l1')
Price_matrix_l2= preprocessing.normalize(Price_matrix, norm='l2')


#print(Price_matrix_l1)
Price_matrix_l2

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])